language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
script: 
- mvn test -f pom.xml
notifications:
  email:
    - sul.gohan@hotmail.fr
    - sophie.bouvry1@gmail.com
    - kenan.lethimonier@etudiant.univ-rennes1.fr
    - margaux.boulle@laposte.net