language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
script: 
- mvn install
- mvn test
- mvn sonar:sonar
addons:
  sonarcloud:
    organization: "elisechap"
    token:
      secure: "a9120031edaf13db44637f19010a6e6cddf20341"

notifications:
  email:
    - chaponelise@gmail.com
