language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
script: 

- mvn sonar:sonar
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
 
addons:
  sonarcloud:
    organization: "sullidai-github"
    token:
      secure: "87cf3a2b8e1af8330051ad6c68f919a45b676203"

notifications:
  email:
    - sophie.bouvry1@gmail.com
    - gogot35@hotmail.fr
