language: java
# use Java 8
jdk:
- oraclejdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false


before_script:
	- mvn install -DskipTests = true -Dmaven .javadoc.skip = true -B -V
	- mvn test -B 

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

