language: java
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
script: 
- mvn test -f pom.xml
mvn sonar:sonar \
  -Dsonar.projectKey=SulliDai_PDL_2018-2019_GR1 \
  -Dsonar.organization=sullidai-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=d319e69da038b7d83aea4f45c06f85f792e78943
notifications:
  email:
    - sophie.bouvry1@gmail.com
    - gogot35@hotmail.fr
